# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc08cece73b2c94a2e215654c4099f187ba73b4cb5c5e57800e94d9ccec39d1f73306d61592e1a1d939af3230ff6249fc122116bd16ff9b8c63c00eeab8881a8

test:
  secret_key_base: 59cb4776df81b3f36e51fd6b0e81d3f14b2ec35f077253e0a79091428eda0e0c4fc2ceeb0f42861b10764c29a6d32edabd411f619cf48f5b3d4a87c983694c55

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
